AllCops:
  NewCops: enable
  Exclude:
    - 'testing/**/*'

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
