deployer:
  user:
  # Uncomment this line if you are not on a shared host/if your web server runs under a different user than what you specified in the user field above
  # www_data_group: www-data
  host:
    staging: 
    production: 
  root: 
  fqdn: 
    staging: 
    production: 
app:
  name:
  repo:
options:
  # Choose from: git-with-submodules, git, scp
  deploy_method: git-with-submodules
  # Use rsync to upload auxialiary content files (set to false if your server doesn't support rsync)
  rsync_enabled: true
