deployer:
  user: 
  host:
    staging: 
    production: 
  root: 
  fqdn: 
    staging: 
    production: 
app:
  name:
  repo:
options:
  deploy_method: git-with-submodules # Choose from: git-with-submodules, git, scp
