deployer:
  user:
  # Uncomment this line if you are not on a shared host/if your web server runs under a different user than what you specified in the user field above
  # www_data_group: www-data
  host:
    staging: 
    production: 
  root: 
  fqdn: 
    staging: 
    production: 
  branch: 
    staging: master
    production: master
  # Uncomment this to create a symlink to the deploy root's current/public at the specified location relative to the deploy root
  # symlink:
    # staging:
    # production:
app:
  name:
  repo:
options:
  # Use rsync to upload auxialiary content files (set to false if your server doesn't support rsync)
  rsync_enabled: true
