version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - "./db/dev:/db"
      - "./db/active:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
  web:
    depends_on:
      - db
    build: .
    volumes:
      - "./public:/var/www/html"
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
